name: images_swiper
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/imWalsh/images_swiper.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  indexed: ^0.0.8
  dismissible_page: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



screenshots:
  - description: "Example of the widget."
    path: images_swiper.gif